#--------------------------------------
# Hugo engine internal settings
#--------------------------------------
baseURL: /

theme: hugo-theme-next

paginate: 3

#--------------------------------------
# Hugo multilingual settings
#--------------------------------------
defaultContentLanguage: zh-cn
languages:
  zh-cn:
    title: NexT
    languageName: 中文
    weight: 1
  en-us:
    title: NexT
    params:
      #------------------------------
      # Reset Site base information
      #------------------------------
      author: Theme NexT
      subtitle: Theme for Hugo
      description: Stay easily & powerful.

#--------------------------------------
# Menus Settings
# Attribute pre is Font Awesome icon name without prefix "fa-".
# External url should start with http:// or https:// .
# -------------------------------------
menus:
  main:
    - identifier: home
      name: 首页
      url: /
      pre: home
      weight: 1
    - identifier: about
      name: 关于
      url: /ablout.html
      pre: user
      weight: 2
    - identifier: archives
      name: 归档
      url: /archives
      pre: archive
      weight: 3
    - identifier: commonweal
      name: 公益 404
      url: /404.html
      pre: heartbeat
      weight: 4


# -------------------------------------
# User-define Settings
# -------------------------------------
params:
  mainSections: [ "posts" ]
  dateFormat: 2006-01-02
  # -------------------------------------
  # Scheme Settings
  # -------------------------------------
  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini

  # Dark Mode
  darkmode: true
  # Browser header panel color.
  themeColor:
    light: "#000"
    dark: "#222"

  #--------------------------------------
  # Site Information Settings
  # -------------------------------------
  author: NexT 主题
  subtitle: 为 Hugo 打造的主题
  description: 保持简单的易用性和强大的功能。
  # Custom logo will use in open graph image meta attribute.
  # Use the "show" variable to control whether displayed in sidebar 
  customLogo: 
    show: false
    url: /imgs/hugo_next_logo.png

  favicon:
    icon: /imgs/icons/favicon.ico
    small: /imgs/icons/favicon_16x16_next.png
    medium: /imgs/icons/favicon_32_32_next.png
    appleTouchIcon: /imgs/icons/apple_touch_icon_next.png

  # Open graph settings
  openGraph:
    enable: true
    #twitter:
    #  card: <twitter:card>
    #  creator: <twitter:creator>
    #  image: <twitter:image>
    #  site: <twitter:site>
    #googlePlus: <g+:profile_link>
    #facebook:
    #  admins: <fb:admin_id>
    #  app_id: <fb:app_id>

  #--------------------------------------
  # Sidebar Settings
  # -------------------------------------
  sidebar:
    # Sidebar Position.
    #position: left | right
    position: left

    # Manual define the sidebar width. If commented, will be default for:
    # Muse | Mist: 320
    # Pisces | Gemini: 240
    width: 256

    # Sidebar Display (only for Muse | Mist), available values:
    #  - post    expand on posts automatically. Default.
    #  - always  expand for all pages automatically.
    #  - hide    expand only when click on the sidebar toggle icon.
    #  - remove  totally remove sidebar including sidebar toggle.
    display: post

    # Sidebar padding in pixels, default 18.
    padding: 18
    # Sidebar offset from top menubar in pixels (only for Pisces | Gemini), default 12.
    offset: 12

  # Sidebar Avatar
  avatar:
    # Replace the default image and set the url here.
    url: /imgs/hugo_next_avatar.png
    # If true, the avatar will be displayed in circle.
    rounded: true
    # If true, the avatar will be rotated with the cursor.
    rotated: true

  # Show Posts / Categories / Tags label in sidebar.
  siteState: true

  # Social Links
  # Usage: `Key: permalink || icon`
  # Key is the link label showing to end users.
  # Value before `||` delimiter is the target permalink, value after `||` delimiter is the name of Font Awesome icon.
  socials: [
    { "GitHub": "https://github.com/yourname || fab fa-github" },
    { "E-Mail": "mailto:yourname@gmail.com || fa fa-envelope" }
    # {"Weibo": "https://weibo.com/yourname || fab fa-weibo"},
    # {"Google": "https://plus.google.com/yourname || fab fa-google"},
    # {"Twitter": "https://twitter.com/yourname || fab fa-twitter"},
    # {"FB Page": "https://www.facebook.com/yourname || fab fa-facebook"},
    # {"StackOverflow": "https://stackoverflow.com/yourname || fab fa-stack-overflow"},
    # {"YouTube": "https://youtube.com/yourname || fab fa-youtube"},
    # {"Instagram": "https://instagram.com/yourname || fab fa-instagram"},
    # {"Skype": "skype:yourname?call|chat || fab fa-skype"}
  ]
  socialIcons:
    enable: true
    iconsOnly: false
    transition: true

  # Creative Commons 4.0 International License.
  # See: https://creativecommons.org/about/cclicenses/
  creativeCommons:
    # Available values: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | cc-zero
    license: by-nc-nd
    # Available values: big | small
    size: big
    sidebar: true
    post: true
    # You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
    # CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
    # No required in here and can be done by multilanguage 
    # language: deed.zh
  
  # Table of Contents in the Sidebar
  # Front-matter variable (nonsupport wrap expand_all).
  toc:
    enable: true
    # Automatically add list number to toc.
    number: true
    # If true, all words will placed on next lines if header width longer then sidebar width.
    wrap: false
    # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
    expandAll: false
    # Maximum heading depth of generated toc.
    maxDepth: 6

  footer:
    # Specify the year when the site was setup. If not defined, current year will be used.
    since: 2016

    # Icon between year and copyright info.
    icon:
      # Icon name in Font Awesome. See: https://fontawesome.com/icons
      name: fa-solid fa-heart
      # If you want to animate the icon, set it to true.
      animated: true
      # Change the color of icon, using Hex Code.
      color: "#FF0000"

    # Powered by Hugo & NexT.
    powered: true

    # Beian ICP and gongan information for Chinese users. See: https://beian.miit.gov.cn, http://www.beian.gov.cn
    beian:
      enable: true
      icp: 粤ICP备18047355-1号
      # The full num of gongan beian which use to query valid.
      gonganNum: 11010102001808

  # Override browsers' default behavior.
  bodyScrollbar:
    # Place the scrollbar over the content.
    overlay: false
    # Present the scrollbar even if the content is not overflowing.
    stable: false

  backTop:
    enable: true
    # Back to top in sidebar.
    sidebar: false
    # Scroll percent label in b2t button.
    scrollPercent: false

  # Reading progress bar
  readingProgress:
    enable: false
    # Available values: left | right
    start: left
    # Available values: top | bottom
    position: top
    reversed: false
    color: "#37c6c0"
    height: 3px

  # Bookmark Support
  bookmark:
    enable: false
    # Customize the color of the bookmark.
    color: "#222"
    # If auto, save the reading progress when closing the page or clicking the bookmark-icon.
    # If manual, only save it by clicking the bookmark-icon.
    save: auto

  # `Follow me on GitHub` banner in the top-right corner.
  githubBanner:
    enable: false
    permalink: https://github.com/yourname
    title: Follow me on GitHub

  codeblock:
    # Code Highlight theme
    # All available themes: https://theme-next.js.org/highlight/
    theme:
      light: default
      dark: stackoverflow-dark
    prism:
      light: prism
      dark: prism-dark
    # Add copy button on codeblock
    copyBtn:
      enable: false
      # Available values: default | flat | mac
      style: defalut

  # Mermaid tag
  mermaid:
    enable: false
    # Available themes: default | dark | forest | neutral
    theme:
      light: default
      dark: dark

  # Note tag (bootstrap callout)
  note:
    # Note tag style values:
    #  - simple    bootstrap callout old alert style. Default.
    #  - modern    bootstrap callout new (v2-v3) alert style.
    #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
    #  - disabled  disable all CSS styles import of note tag.
    style: simple
    icons: false
    # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
    # Offset also applied to label tag variables. This option can work with disabled note tag.
    light_bg_offset: 0

  # Tabs tag
  tabs:
    # Make the nav bar of tabs with long content stick to the top.
    sticky: false
    transition:
      tabs: false
      labels: true

  # PDF tag
  # NexT will try to load pdf files natively, if failed, pdf.js will be used.
  # So, you have to install the dependency of pdf.js if you want to use pdf tag and make it available to all browsers.
  # Dependencies: https://github.com/next-theme/theme-next-pdf
  pdf:
    enable: false
    # Default height
    height: 500px

  # Show Views / Visitors of the website / page with busuanzi.
  # For more information: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi:
    enable: false
    visitors: true
    visitorsIcon: fa fa-user
    views: true
    viewsIcon: fa fa-eye
    postViews: true
    postViewsIcon: far fa-eye

  # ---------------------------------------------------------------
  # Search Services
  # See: https://theme-next.js.org/docs/third-party-services/search-services
  # ---------------------------------------------------------------

  # Algolia Search
  # For more information: https://www.algolia.com
  algoliaSearch:
    enable: false
    hits:
      perPage: 10

  # Local Search
  # Dependencies: https://github.com/next-theme/hexo-generator-searchdb
  localSearch:
    enable: false
    # If auto, trigger search by changing input.
    # If manual, trigger search by pressing enter key or search button.
    trigger: auto
    # Show top n results per article, show all results by setting to -1
    #top_n_per_article: 1
    # Unescape html strings to the readable one.
    unescape: false
    # Preload the search data when the page loads.
    preload: false

  # Reduce padding / margin indents on devices with narrow width.
  mobileLayoutEconomy: false


