#--------------------------------------
# Hugo engine internal settings
#--------------------------------------
baseURL: /

theme: hugo-theme-next

#--------------------------------------
# Hugo multilingual settings
#--------------------------------------
defaultContentLanguage: zh-cn
languages:
  zh-cn:
    title: NexT
    languageName: 中文
    weight: 1
  en-us:
    title: NexT
    params:
      #------------------------------
      # Reset Site base information
      #------------------------------
      author: Theme NexT
      subtitle: Theme for Hugo
      description: Stay easily & powerful.

# -------------------------------------
# User-define Settings
# -------------------------------------
params:
  # -------------------------------------
  # Scheme Settings
  # -------------------------------------

  # Schemes
  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini

  # Dark Mode
  darkmode: true

  #--------------------------------------
  # Site Information Settings
  # -------------------------------------
  author: NexT 主题
  subtitle: 为 Hugo 打造的主题
  description: 保持简单的易用性和强大的功能。
  # Custom logo will use in open graph image meta attribute.
  # Use the "show" variable to control whether displayed in sidebar 
  customLogo: 
    show: false
    url: /imgs/hugo-next-logo.png

  favicon:
    icon: /imgs/icons/favicon.ico
    small: /imgs/icons/favicon-16x16-next.png
    medium: /imgs/icons/favicon-32x32-next.png
    appleTouchIcon: /imgs/icons/apple-touch-icon-next.png

  # Open graph settings
  openGraph:
    enable: true
    #twitter:
    #  card: <twitter:card>
    #  creator: <twitter:creator>
    #  image: <twitter:image>
    #  site: <twitter:site>
    #googlePlus: <g+:profile_link>
    #facebook:
    #  admins: <fb:admin_id>
    #  app_id: <fb:app_id>

  sidebar:
    # Sidebar Position.
    #position: left | right
    position: left

    # Manual define the sidebar width. If commented, will be default for:
    # Muse | Mist: 320
    # Pisces | Gemini: 240
    width: 256

    # Sidebar Display (only for Muse | Mist), available values:
    #  - post    expand on posts automatically. Default.
    #  - always  expand for all pages automatically.
    #  - hide    expand only when click on the sidebar toggle icon.
    #  - remove  totally remove sidebar including sidebar toggle.
    display: post

    # Sidebar padding in pixels, default 18.
    padding: 18
    # Sidebar offset from top menubar in pixels (only for Pisces | Gemini), default 12.
    offset: 12

  # Sidebar Avatar
  avatar:
    # Replace the default image and set the url here.
    url: /imgs/hugo-next-avatar.png
    # If true, the avatar will be displayed in circle.
    rounded: true
    # If true, the avatar will be rotated with the cursor.
    rotated: true

  # Show Posts / Categories / Tags label in sidebar.
  siteState: true

  # Social Links
  # Usage: `Key: permalink || icon`
  # Key is the link label showing to end users.
  # Value before `||` delimiter is the target permalink, value after `||` delimiter is the name of Font Awesome icon.
  socials: [
    { "GitHub": "https://github.com/yourname || fab fa-github" },
    { "E-Mail": "mailto:yourname@gmail.com || fa fa-envelope" }
    # {"Weibo": "https://weibo.com/yourname || fab fa-weibo"},
    # {"Google": "https://plus.google.com/yourname || fab fa-google"},
    # {"Twitter": "https://twitter.com/yourname || fab fa-twitter"},
    # {"FB Page": "https://www.facebook.com/yourname || fab fa-facebook"},
    # {"StackOverflow": "https://stackoverflow.com/yourname || fab fa-stack-overflow"},
    # {"YouTube": "https://youtube.com/yourname || fab fa-youtube"},
    # {"Instagram": "https://instagram.com/yourname || fab fa-instagram"},
    # {"Skype": "skype:yourname?call|chat || fab fa-skype"}
  ]
  socialIcons:
    enable: true
    iconsOnly: false
    transition: true

  # Creative Commons 4.0 International License.
  # See: https://creativecommons.org/about/cclicenses/
  creativeCommons:
    # Available values: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | cc-zero
    license: by-nc-nd
    # Available values: big | small
    size: big
    sidebar: true
    post: true
    # You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
    # CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
    # No setting is required here and can be done by multilanguage 
    # language: deed.zh


